### ISSUE TITLE
Not sure if FFT benchmark is fair.

### ISSUE THREAD

**Issue by ali-ramadhan** [glwagner/CuSpeedTests#2]
The FFT speedups seemed a little too low until I noticed that the FFT benchmark is timing both an FFT and an `ldiv!` operation which I suspect is dominating the test. 

I guess by "not fair" I mean that benchmarking `ldiv!` shouldn't be part of an FFT benchmark.

This is just with 1 thread on the CPU but then you see a ~325x speedup for `Float32`.
```
julia> xc = rand(Complex{Float32}, 256, 256, 256);
julia> @benchmark FFTW.fft!(xc)
BenchmarkTools.Trial: 
  memory estimate:  3.16 KiB
  allocs estimate:  48
  --------------
  minimum time:     955.098 ms (0.00% GC)
  median time:      965.250 ms (0.00% GC)
  mean time:        967.959 ms (0.00% GC)
  maximum time:     982.259 ms (0.00% GC)
  --------------
  samples:          6
  evals/sample:     1

julia> xg = CuArray(rand(Complex{Float32}, 256, 256, 256));

# @benchmark ends up running too often and the GPU runs out of memory.
julia> @time CuArrays.@sync fft!(xg);
  0.002962 seconds (13 allocations: 624 bytes)
```

**Comment by glwagner** [comment]
`ldiv!` performs an inverse fft.

**Comment by ali-ramadhan** [comment]
Huh... I'm kind of surprised that it's that slow then as IFFT performance should be similar to FFT performance.

I thought `ldiv!` inverts a matrix: https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html#LinearAlgebra.ldiv!

**Comment by glwagner** [comment]
The syntax for pre-planned, non-allocating FFTs uses `mul!` (notionally matrix multiplication) and `ldiv!` (notionally left matrix division) for forward and backward FFTs:

https://juliamath.github.io/AbstractFFTs.jl/stable/implementations/#Defining-a-new-implementation-1

The FFT algorithm can be interpreted as simply a fast, `n log(n)` implementation of a ordinarily `n^2` matrix multiplication.

**Comment by glwagner** [comment]
Multithreaded FFTs scale very well. So an 8-thread FFT should be about 8 times faster than a 1-thread FFT.

But we should also note that benchmarks are not portable. They are particular to both the CPU and GPUs used.

**Comment by ali-ramadhan** [comment]
Ah interesting. In Oceananigans we have two different plans (forward and backward) and apply them using `*`.

Even with 8 threads the benchmarks feel a little low but yeah I can't go around judging benchmarks on "feeling".

**Comment by ali-ramadhan** [comment]
Misunderstanding.

**Comment by glwagner** [comment]
Also the inplace fft scales differently from out-of-place. 

Perhaps we can compare forward and backward ffts separately. I think my original logic was that in a normal algorithm if you perform a forward fft, you're going to perform a backward fft too. So its relevant sense to benchmark the combination.

**Comment by ali-ramadhan** [comment]
Agreed that benchmarking both makes sense.

The only difference should be a minus sign in the exponential so I'd be surprised if forward and backward FFTs perform differently.

**Comment by glwagner** [comment]
Yeah, I agree it'd be surprising. On the other hand, a different plan is calculated and executed for forward versus inverse... hmm! I think I was using the "super conservative and blindly overthorough" approach.
